# Generated by Django 4.2.15 on 2024-09-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_authors_tagauthors_todayupdate_authorposts'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoEarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'InfoEarn',
                'verbose_name_plural': 'InfoEarns',
            },
        ),
        migrations.CreateModel(
            name='CommentAndInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('personal_info', models.CharField(blank=True, max_length=210, verbose_name='Personal Info')),
                ('gmail', models.CharField(blank=True, max_length=210, verbose_name='Gmail')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.authors', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'CommentInfo',
                'verbose_name_plural': 'CommentsInfo',
            },
        ),
    ]
